# Generated by Django 4.2.5 on 2023-10-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracks',
            new_name='Track',
        ),
    ]
