# Generated by Django 4.2.5 on 2023-10-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0002_rename_tracks_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='track',
            name='title',
        ),
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='popularity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(to='spotifier.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='duration_ms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='popularity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
