# Generated by Django 4.2.5 on 2023-10-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0003_remove_artist_genre_remove_track_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration_ms',
            field=models.IntegerField(default=0),
        ),
    ]
