# Generated by Django 4.2.6 on 2023-10-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0008_alter_track_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='preview_url',
        ),
    ]
