# Generated by Django 4.2.6 on 2023-10-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0009_remove_track_preview_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackClone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_local', models.BooleanField(default=True)),
                ('is_playable', models.BooleanField(default=True)),
                ('popularity', models.IntegerField(default=0)),
                ('track_number', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('duration_ms', models.IntegerField(default=0)),
                ('release_date', models.CharField(blank=True, max_length=30, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(blank=True, null=True, upload_to='')),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='artists',
        ),
        migrations.DeleteModel(
            name='CloneTime',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.AddField(
            model_name='trackclone',
            name='TrackFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotifier.trackfile'),
        ),
        migrations.AddField(
            model_name='trackclone',
            name='artists',
            field=models.ManyToManyField(to='spotifier.artist'),
        ),
    ]
