# Generated by Django 4.2.6 on 2023-10-15 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0010_trackclone_trackfile_remove_track_artists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackclone',
            name='TrackFile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotifier.trackfile'),
        ),
        migrations.AlterField(
            model_name='trackclone',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
