# Generated by Django 4.2.6 on 2023-10-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0011_alter_trackclone_trackfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='image_url',
        ),
    ]
