# Generated by Django 4.2.6 on 2023-11-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0012_remove_artist_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackclone',
            name='spotify_link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
