# Generated by Django 4.2.6 on 2023-11-03 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spotifier", "0013_trackclone_spotify_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackclone",
            name="spotify_link",
        ),
    ]
