# Generated by Django 4.2.6 on 2023-11-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotifier", "0014_remove_trackclone_spotify_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackclone",
            name="downloaded",
            field=models.BooleanField(default=False),
        ),
    ]
