# Generated by Django 4.2.6 on 2024-02-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0018_remove_trackclone_trackfile_delete_trackfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackclone',
            name='acousticness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackclone',
            name='danceability',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackclone',
            name='energy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackclone',
            name='instrumentalness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackclone',
            name='key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackclone',
            name='liveness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackclone',
            name='loudness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackclone',
            name='mode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackclone',
            name='speechiness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackclone',
            name='tempo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackclone',
            name='time_signature',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trackclone',
            name='valence',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trackclone',
            name='duration_ms',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
