# Generated by Django 4.2.6 on 2024-02-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0019_trackclone_acousticness_trackclone_danceability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackclone',
            name='feature_cloned',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
