# Generated by Django 4.2.6 on 2024-02-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0020_trackclone_feature_cloned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackclone',
            name='downloaded',
        ),
        migrations.RemoveField(
            model_name='trackclone',
            name='feature_cloned',
        ),
        migrations.RemoveField(
            model_name='trackclone',
            name='is_local',
        ),
        migrations.RemoveField(
            model_name='trackclone',
            name='is_playable',
        ),
    ]
