# Generated by Django 4.2.6 on 2024-02-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0021_remove_trackclone_downloaded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackclone',
            name='created',
        ),
        migrations.RemoveField(
            model_name='trackclone',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='trackclone',
            name='type',
        ),
        migrations.AddField(
            model_name='trackclone',
            name='music_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
