# Generated by Django 4.2.6 on 2024-02-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0022_remove_trackclone_created_remove_trackclone_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackclone',
            name='music_type',
        ),
    ]
