# Generated by Django 4.2.6 on 2024-03-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0024_remove_trackclone_track_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackclone',
            name='downloaded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
