# Generated by Django 4.2.6 on 2024-03-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0025_trackclone_downloaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackclone',
            name='downloaded',
        ),
        migrations.AddField(
            model_name='trackclone',
            name='undownloaded',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
