# Generated by Django 4.2.6 on 2024-03-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifier', '0026_remove_trackclone_downloaded_trackclone_undownloaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackclone',
            old_name='undownloaded',
            new_name='downloaded',
        ),
    ]
